#!/usr/bin/php
<?php
// Jason Brillante "Damdoshi"
// Pentacle Technologie 2008-2022
// Hanged Bunny Studio 2014-2021
// EFRITS SAS 2022
//
// WorkSpy

// Un clef SSH doit déjà avoir été échangé.
function SendData($url, $data)
{
    if (($data = json_encode($data, JSON_UNESCAPED_SLASHES)) == NULL)
	return (NULL);
    $cmd = "echo '$data' | ssh -tt -o StrictHostKeyChecking=no infosphere_hand@$url -t infosphere_hand 2> /dev/null";
    $ret = shell_exec($cmd);
    return (json_decode($ret));
}

if ($argc < 2)
   $argv[1] = "192.168.200.1";

$url = $argv[1];
$packet["mac"] = trim(file_get_contents("/sys/class/net/eno1/address"));
$packet["name"] = trim(file_get_contents("/proc/sys/kernel/hostname"));
$packet["command"] = "log";

do
{
    $packet["users"] = explode("\n", trim(shell_exec("who | cut -d ' ' -f 1 | sort | uniq")));
    $packet["date"] = trim(date("d/m/Y H:i:s", time()));
    $packet["lock"] = file_exists("/tmp/block");
    SendData($url, $packet);
    system("sleep 5.0");
}
while (1);
exit(0);
